# =============================================
# PriceWise ProGuard Rules
# =============================================

# ---------- Retrofit + OkHttp ----------
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions
-keepattributes *Annotation*

# Keep Retrofit service interfaces
-keep,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# ---------- Moshi ----------
-keep class com.squareup.moshi.** { *; }
-keep @com.squareup.moshi.JsonClass class * { *; }
-keepclassmembers class * {
    @com.squareup.moshi.Json <fields>;
    @com.squareup.moshi.FromJson <methods>;
    @com.squareup.moshi.ToJson <methods>;
}
# Keep Moshi adapters generated by KSP
-keep class **JsonAdapter { *; }

# ---------- API Models (serialization) ----------
-keep class com.alvaro.pricewise.data.model.** { *; }

# ---------- Hilt ----------
-dontwarn dagger.hilt.**
-keep class dagger.hilt.** { *; }
-keep class * extends dagger.hilt.android.lifecycle.HiltViewModel

# ---------- Compose ----------
-dontwarn androidx.compose.**

# ---------- Coroutines ----------
-dontwarn kotlinx.coroutines.**

# ---------- JWT / jjwt ----------
-dontwarn io.jsonwebtoken.**

# ---------- DataStore ----------
-keep class androidx.datastore.** { *; }

# ---------- Google Sign-In / Credentials ----------
-keep class com.google.android.libraries.identity.** { *; }
-keep class androidx.credentials.** { *; }

# ---------- General ----------
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
